const songs = [
  {
    id: 1,
    artist: "Coldplay",
    title: "Yellow",
    album: "Parachutes",
    coverArt: "https://upload.wikimedia.org/wikipedia/commons/6/68/ChrisMartinManch030623_%28cropped%29.jpg",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 2,
    artist: "Adele",
    title: "Hello",
    album: "25",
    coverArt: "https://upload.wikimedia.org/wikipedia/en/1/1b/Adele_-_21.png",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 3,
    artist: "Ed Sheeran",
    title: "Shape of You",
    album: "÷ (Divide)",
    coverArt: "https://upload.wikimedia.org/wikipedia/en/4/45/Divide_cover.png",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 4,
    artist: "Drake",
    title: "God's Plan",
    album: "Scorpion",
    coverArt: "https://i1.sndcdn.com/artworks-000463468011-ws8yh6-t500x500.jpg",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 5,
    artist: "Taylor Swift",
    title: "Love Story",
    album: "Fearless",
    coverArt: "https://imageio.forbes.com/specials-images/imageserve/646e6affb9a2a85595a62c39/0x0.jpg?format=jpg&crop=1573,1574,x239,y256,safe&height=416&width=416&fit=bounds",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 6,
    artist: "The Weeknd",
    title: "Blinding Lights",
    album: "After Hours",
    coverArt: "https://preview.redd.it/what-the-weeknd-songs-are-100-perfect-in-your-opinion-v0-gemrdzy9p5w91.jpg?auto=webp&s=c171d10338521b7ac021490d4998e85a5c6e1183",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 7,
    artist: "Billie Eilish",
    title: "Bad Guy",
    album: "When We All Fall Asleep, Where Do We Go?",
    coverArt: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/BillieEilishO2160622_%2819_of_45%29_%2852153214339%29_%28cropped_3%29.jpg/250px-BillieEilishO2160622_%2819_of_45%29_%2852153214339%29_%28cropped_3%29.jpg",
    url:"https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 8,
    artist: "Imagine Dragons",
    title: "Believer",
    album: "Evolve",
    coverArt: "https://upload.wikimedia.org/wikipedia/en/b/b5/ImagineDragonsEvolve.jpg",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 9,
    artist: "Dua Lipa",
    title: "Levitating",
    album: "Future Nostalgia",
    coverArt: "https://upload.wikimedia.org/wikipedia/en/f/f5/Dua_Lipa_-_Future_Nostalgia_%28Official_Album_Cover%29.png",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 10,
    artist: "Post Malone",
    title: "Circles",
    album: "Hollywood's Bleeding",
    coverArt: "https://upload.wikimedia.org/wikipedia/en/a/a5/Post_Malone_-_Circles.png",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 11,
    artist: "Bruno Mars",
    title: "24K Magic",
    album: "24K Magic",
    coverArt: "https://cdn-images.dzcdn.net/images/artist/7f3c0956357c326b2db2cf436f1dc8c5/1900x1900-000000-80-0-0.jpg",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 12,
    artist: "Maroon 5",
    title: "Sugar",
    album: "V",
    coverArt: "https://i1.sndcdn.com/artworks-000107338750-5bxgf8-t500x500.jpg",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 13,
    artist: "Justin Bieber",
    title: "Peaches",
    album: "Justice",
    coverArt: "https://upload.wikimedia.org/wikipedia/commons/d/da/Justin_Bieber_in_2015.jpg",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 14,
    artist: "Olivia Rodrigo",
    title: "Drivers License",
    album: "SOUR",
    coverArt: "https://assets.vogue.com/photos/600b0497f9a1b521a80915dc/master/pass/001-Olivia-Rodrigo-vogue-200121-creditCredit-ERICA-HERNÁNDEZ.jpg",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 15,
    artist: "Doja Cat",
    title: "Woman",
    album: "Planet Her",
    coverArt: "https://static01.nyt.com/images/2023/09/04/arts/01playlist/01playlist-superJumbo.jpg",
    url:"https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
  {
    id: 16,
    artist: "Harry Styles",
    title: "As It Was",
    album: "Harry's House",
    coverArt: "https://assets.vogue.com/photos/6246bad295e5c52287d15b55/master/w_1600%2Cc_limit/Main%2520Image%2520PC_%2520Hanna%2520Moon-min.jpg",
    url: "https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
  },
];

module.exports = songs;
